i18n:
  structure: multiple_folders
  locales: [ nl, en ]
  default_locale: nl
backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: "duplicate" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false, i18n: true }
      - { label: "Cover", name: "cover", widget: "image", required: false, i18n: "duplicate" }
      - { label: "Tags", name: "tags", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

