i18n:
  structure: multiple_folders
  locales: [ nl, en ]
  default_locale: nl
backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "slideshow"
    label: "Slideshow"
    label_singular: "Slide"
    folder: "content/slideshow"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "image", required: false, i18n: "duplicate" }
  - name: "schedule"
    label: "Schedule"
    label_singular: "Schedule"
    folder: "content/schedule"
    create: true
    i18n: true
    fields:
      - { label: "Day", name: "day", widget: "string", i18n: true }
      - { label: "Time", name: "time", widget: "string", i18n: true }
      - { label: "Title", name: "title", widget: "string", i18n: true }
  - name: "memberschip"
    label: "Memberschip"
    label_singular: "Membership"
    folder: "content/memberschip"
    create: true
    i18n: true
    fields:
      - { label: "Membership type", name: "membership_type", widget: "string", i18n: true }
      - { label: "Weekly sessions", name: "weekly_sessions", widget: "string", i18n: true }
      - { label: "Price per 6 months", name: "price_per_6_months", widget: "string", i18n: true }
      - { label: "Price per year", name: "price_per_year", widget: "string", i18n: true }
  - name: "home"
    label: "Home"
    label_singular: "Home" # Used in the UI, ie: "New Post"
    folder: "content/home"
    create: true
    i18n: true
    fields:
      - { label: "Type", name: "type", widget: "select", i18n: false, options: ["news_left_and_image_right", "news_right_and_image_left", "centered_text", "only_text"] }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "image", required: false, i18n: "duplicate" }
      - { label: "Body", name: "body", widget: "text", i18n: true }
