i18n:
  structure: multiple_folders
  locales: [ nl, en ]
  default_locale: nl
backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "slideshow"
    label: "Slideshow"
    label_singular: "Slide"
    folder: "content/slideshow"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "image", required: false, i18n: "duplicate" }
  - name: "schedule"
    label: "Schedule"
    label_singular: "Schedule"
    folder: "content/schedule"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Day", name: "day", widget: "select", i18n: false, options: ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"]}
      - { label: "From", name: "from", widget: "datetime", i18n: false, date_format: false, time_format: 'HH:mm' }
      - { label: "Until", name: "until", widget: "datetime", i18n: false, date_format: false, time_format: 'HH:mm' }
  - name: "paytoplay"
    label: "Pay to Play"
    label_singular: "Pay to play"
    folder: "content/paytoplay"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Price", name: "price", widget: "string", i18n: false }
  - name: "membership"
    label: "Membership"
    label_singular: "Membership"
    folder: "content/membership"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Weekly sessions", name: "weekly_sessions", widget: "string", i18n: false }
      - { label: "Price per 6 months", name: "price_per_6_months", widget: "string", i18n: false }
      - { label: "Price per year", name: "price_per_year", widget: "string", i18n: false }
  - name: "downloads"
    label: "Downloads"
    label_singular: "Downloads"
    folder: "content/downloads"
    create: true
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "File", name: "file", widget: "file", i18n: true }
  - name: "home"
    label: "Home"
    label_singular: "Home" # Used in the UI, ie: "New Post"
    folder: "content/home"
    create: true
    i18n: true
    fields:
      - { label: "Type", name: "type", widget: "select", i18n: false, options: ["news_left_and_image_right", "news_right_and_image_left", "centered_text", "only_text"] }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Image", name: "image", widget: "image", required: false, i18n: "duplicate" }
      - { label: "Body", name: "body", widget: "text", i18n: true }
